### ISSUE TITLE
There is question about the filter

### ISSUE THREAD

**Issue by ideapad2009** [XGudron/UA3REO-DDC-Transceiver#2]
Dear:
     I made a simulation in multisim about the filter. It seemed like there is a large ripple in pass band. 
Like the 1.4-2.8MHZ filter below:
    The gain at 1.4MHZ is -12db and -1.8db at 2.0MHz. Maybe there is a some  error in simulation.
![1 4-2 8M filter](https://user-images.githubusercontent.com/52630859/98788402-d29b5e00-243b-11eb-9cbb-929e7959d1fe.png)

**Comment by XGudron** [comment]
I confirm, there is an error in the calculations of some filters, I will fix it in the next version Thank you for bringing this to your attention.

**Comment by XGudron** [comment]
Fixed in 2.0.4 version
