### ISSUE TITLE
The BOM file of RF-UNIT-QRP-RU4PN-rev3

### ISSUE THREAD

**Issue by liuyang0690** [XGudron/UA3REO-DDC-Transceiver#32]
hi, I chose rf-unit-qrp-ru4pn-rev3 as the RF board of Wolf, but I did not find the BOM file or iBom file of this board, could you please provide it?  In addition, the iBom file version of the motherboard is applicable to rev30, but the bom file version has been updated to rev33. Could you please update it? It will greatly facilitate the purchase of components and soldered .Thank you very much.

**Comment by XGudron** [comment]
Hello!

The author of the RU4PN board did not send a bom file, you can contact him on telegram, his nickname is https://t.me/AllQSO

Updated assembly file for rev33 https://github.com/XGudron/UA3REO-DDC-Transceiver/blob/dev/Schematic/Wolf/Assembly/ASSEMBLY-MOTHERBOARD-rev33.PDF
Bom for rev33 https://github.com/XGudron/UA3REO-DDC-Transceiver/blob/dev/Schematic/Wolf/BOM/BOM-MOTHERBOARD-rev33.xlsx
