### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by StevenSaH** [XGudron/UA3REO-DDC-Transceiver#38]
Hello Dimitry, 
your commit 32d5e147aeb82b4fbdb066feb1a73412100a8d72 Pager buttons color update removes some variables from a structure which are still in use! Like BUTTON_BACK in line 231 of lcd.c ;) 

so i will receive a compile error for Wolf 7" with GT911

**Comment by StevenSaH** [comment]
fixed

**Comment by XGudron** [comment]
Thank you!
