### ISSUE TITLE
Upgrading firmware

### ISSUE THREAD

**Issue by Starmike98** [XGudron/UA3REO-DDC-Transceiver#40]
I have looked everywhere but can’t find any instructions on how to upgrade the software ob my Wolf.  I am on version 6.8 and want to get up on version 8.  Can I get some help on this?

**Comment by StevenSaH** [comment]
Short Boot0 
or use in Settings DFU Mode (but for this the Battiery must work), start the Wolf and use STM32Cube to flash the BIN File

**Comment by StevenSaH** [comment]
look here for further Informations

https://github.com/XGudron/UA3REO-DDC-Transceiver/issues/36

**Comment by Starmike98** [comment]
But how do you do DFU mode?   Do I hook something up to the USB port for that?   I am really a novice at this

**Comment by StevenSaH** [comment]
Install STM32Cube and download the latest STM32 Firmware

https://www.dropbox.com/sh/jrs38c2iwtxk6c1/AACUw9yrOuv3P8LjwSxlcpqIa?dl=0

Install STM32Cube

install the Boot0 Jumper on the WolfMainboard
Power on the Wolf (you must  hold the Poweron Button the whole time during flashing!!)
your Computer should now see the Wolf in DFU Mode, press in STM32Cube in the top right corner connect, choose the bin file and upload it to the stm

**Comment by StevenSaH** [comment]
There is a Telegram group for these types of questions.
You can get help there quicker than opening a case here

https://t.me/TRX_Wolf

**Comment by Starmike98** [comment]
Thanks.  I am still really confused.  I looked at the Telegram chat but looks like it is all in Russian.  Sorry.  I am on version 6.8 so I should not choose the OTA update.  So if I open up the radio, take out the SD card, put it in my computer and put the new software on the card. Put the card back in the radio and then go though the updates from their.  Do you do STM first then FPGA or the other way

**Comment by StevenSaH** [comment]
You can write there in english

on 6.8 flashing by SD Card could also fail! I dont know how big the selfupdate error was in 6.8. i could be only the FPGA update, but also the STM32 update!

When the STM32 Firmware file is on the SD choose
F8 than SD Card than FileManager, choose the BIN file and choose flash ..

When you changed the STM32 to a newer Version, you has to update the FPGA too.
When you has to do this manualy you need the USBBlaster on the JTAG connection, so be carefull with the updateprocess, and ask in the telegram channel if it is possible to do it on this way! i used stm32 and usb blaster to move from 6.8 to 7.0!

**Comment by Starmike98** [comment]
I am on telegram and it is set to English bit all the post are still in Russian.  is there any way to translate them?

**Comment by f4exb** [comment]
May be off topic but this is just to help you... You need to subscribe to Telegram premium to translate all messages at once. Else in the language menu enable the translate button then you can translate individual messages by right clicking on the message and choose "Translate".

**Comment by XGudron** [comment]
https://github.com/XGudron/UA3REO-DDC-Transceiver/wiki/How-to-flash-a-Wolf-transceiver

**Comment by Starmike98** [comment]
I got files over to the SD card. Started flashing FPGA.  Now I am getting EEPROM ERROR.  I was told to use St-Link to manually go in and flash.  Ordered an ST LINK device.  Is there any documentation on how to hook the st link device to the board on the Wolf?   Thanks

**Comment by Starmike98** [comment]
I have also ordered the USB BLASTER.  Since it is the FPGA that is corrupted, I saw your procedure for using USB blaster to fix it.  Hopefully that will get me back up and running

**Comment by Starmike98** [comment]
Got the USB Blaster installed and Quartus 13.1.  Computer sees the Blaster but can go any further.  Says the chain is broken.  Any hints to get me moving ahead

**Comment by Starmike98** [comment]
I guess no one knows

**Comment by Starmike98** [comment]
> https://github.com/XGudron/UA3REO-DDC-Transceiver/wiki/How-to-flash-a-Wolf-transceiver

This is the process I followed.  Thought it would be easy but it is not

**Comment by StevenSaH** [comment]
It is easy... when you do exact the steps like in the howto it has to work.

Post a screenshot of your error, make a image of how you connect everthing

**Comment by Starmike98** [comment]
Do you need to do the boot jumper for this or not.  How do you keep the radio from booting so you can flash

**Comment by StevenSaH** [comment]
the boot0 jumper is only needed to programm the STM32

turn off the radio
connect the usb blaster
connect the usb blaster with the pc
turn on the radio (it will do a normal startup)
programm the fpga
turn off the radio
disconnect the usb blaster 
turn the radio on

**Comment by Starmike98** [comment]
![IMG_0881](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/a54aaea0-d099-44e5-ba99-582e710a3784)
![IMG_0880](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/6feb916e-
![IMG_0875](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/256f7aa1-8b23-4b68-881d-006297d34b8c)
![IMG_1612](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/2898121e-a79e-40f4-859b-134dc27f12f3)
![IMG_0866](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/dd55273f-1c7a-42e5-a8b8-8b8733def460)
![IMG_0865](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/22d8cb08-a87b-4083-baf1-38e1ec2afa7a)
![IMG_1611](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/8a00f589-61b9-49cb-82dc-b30b3f1f9fee)
74c5-4f43-b805-541040c88228)
![IMG_0879](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/ef7fb3c5-6ad0-4df0-90d7-3acf7258d154)
![IMG_0878](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/5e3c7342-9cdf-4dbc-a599-70e6edbad8d4)
![IMG_0876](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/bd750661-5418-4aa8-9f23-3b27fe33a994)

**Comment by Starmike98** [comment]
![IMG_1625](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/3358e6cf-62ca-456b-9a12-6f7e0fff1555)
![IMG_1626](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/8368088a-a3b2-4415-8aab-39753c0d50e5)
![IMG_1627](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/e23d6250-c2da-4b8e-9d9e-407c3c796104)
![IMG_1628](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/ea9eb060-c419-466b-bb53-aea33331af9b)

**Comment by Starmike98** [comment]
Those are the steps I did.  Here are screenshots

**Comment by StevenSaH** [comment]
🤔
the radio was turned on? and no boot0 connection?

! When you close the boot0 jumper, the radio will not start, it only has power when you press and hold the power button, this is only for programming the STM !

you radio has to do a normal startup, but with connected USB Blaster. 

you error messages says that the fpga was not found, and could not accessed.

**Comment by Starmike98** [comment]
Yes, radio is on.  Blank RED screen.  No boot0 jumper (I dont even know where that is at...lol), USB Blaster connected and powered by the computer when I turned on the radio

**Comment by Starmike98** [comment]
Sorry to keep bugging you about this.  I went on telegram and they said to search the internet to find an original USB Blaster.  Like how would I know which is the original

**Comment by Starmike98** [comment]
I order a different version from Amazon.  Wil be here tomorrow.  maybe something is wacky about the one i have

**Comment by StevenSaH** [comment]
thats possible, but the red screen is not good..
is there more information about the error this.red screen shows??

**Comment by Starmike98** [comment]
The RED screen first says
Loaded Default settings
then 
EEPROM Error
then 
Loaded default calibrations
then EEPROM Error (again)
Then the normal screen comes up briefly (which makes you think it is working) but spectrum part is blank
then goes to a blank RED screen

**Comment by Starmike98** [comment]
This is a Chinese version

**Comment by Starmike98** [comment]
![IMG_1629](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/d3e60cca-fce1-4d23-807a-40328c42a34d)
![IMG_1630](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/c9b56b56-fe64-4450-89c6-1b92981bd3b2)
![IMG_1631](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/c9900f79-39e7-4ef3-8bcb-1cc1fa0f69e0)
![IMG_1632](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/0a825726-08c3-44ad-b7be-5bfd727329fe)
![IMG_1633](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/c11b2ea3-c1f5-4fa2-ab04-6829b7f5edef)

**Comment by StevenSaH** [comment]
Hmmm there is something wrong with the W25Q16 U7, but i could be because the fpga is not starting.

When the error is still there when you has updated the fpga, than you has to take a closer look

**Comment by Starmike98** [comment]
![IMG_1634](https://github.com/XGudron/UA3REO-DDC-Transceiver/assets/147280421/33d19dda-aed3-42ac-86ba-9eb7ca48104f)

**Comment by Starmike98** [comment]
I assume the FPGA controls the spectrum scope so hat is why it is blank.  Nothing else comes up on the screen when i try to update FPGA

**Comment by StevenSaH** [comment]
the stm gets some clocks from the fpga to access spi devices.
when the fpga does not work, this error could be possible, and your empty waterfall is a indicator that there is something wrong at the fpga

**Comment by StevenSaH** [comment]
first try the other blaster
when this do es not.work replace the fpga

**Comment by Starmike98** [comment]
Thanks for all the help

**Comment by Starmike98** [comment]
Sorry for my ignorance, is the fpga a chip?  Where would i get one if i needed one?

**Comment by StevenSaH** [comment]
yes it a chip

https://www.digikey.de/de/products/detail/intel/EP4CE22E22C8N/2288353

not easy to solder for a untrained person, maybe you can ask a ham to help you

**Comment by StevenSaH** [comment]
Maybe  wd8bxs  can help you, he sometime builds mcHF for other hams in the US

https://www.digikey.de/de/products/detail/intel/EP4CE22E22C8N/2288353

**Comment by Starmike98** [comment]
Hi, The new USB Blaster worked. Got the radio up and running. So then flashed STM form the SF card so they would be on the same version. After it flashed, the screen went BLACK. How long is it supposed to stay black?

This is what happened when I ORIGINALLY FLASH FPGA.  Screen went black.  So when I unplugged it from the power, it got the EEPROM Error.  So I am scared to touch it

**Comment by Starmike98** [comment]
Now it will not power on, so it did not like version 8.1 STM.  I am not sure where to go from here
