### ISSUE TITLE
FPGA

### ISSUE THREAD

**Issue by takimp** [XGudron/UA3REO-DDC-Transceiver#47]
Hello,
Which version of Quartus do we use for compiling the FPGA code ?
I'm trying with version 22.1 but I can't open the project file with error of "it's only can be opened using pro version (v23.0). I tried with v23.0, but there is no support for Cyclone IV.

Thanks

**Comment by XGudron** [comment]
Hello! I use "Quartus 22.1 Standart" version

**Comment by takimp** [comment]
Hello, finally  I open the project successfully.
The issue is I have opened the project file before using Pro version and the qdb folder must be deleted before reopen it using Standard version.
Now issue is resolved.
